workflows:

  - &build_workflow
    name: Faster CI / build (5.3.0)
    image: us.gcr.io/fasterci/bazelbuilder:d278ee1
    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - "**"
    steps:
      - name: Build & test
        run: |
          tar -xf filetargz; chmod u+x *
